export const SUCCESS_ADD_ITEM = 'SUCCESS_ADD_ITEM'
export const SUCCESS_GET_ITEMS = 'SUCCESS_GET_ITEMS'
export const SUCCESS_DELETE_ITEM = 'SUCCESS_DELETE_ITEM'
export const SUCCESS_SEARCH_ITEMS = 'SUCCESS_SEARCH_ITEMS'